# Generated by Django 5.1.5 on 2025-01-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_created_at_tour_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('vehicle', models.CharField(max_length=100, verbose_name='Veículo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('information', models.TextField(verbose_name='Informações Adicionais')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
            },
        ),
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('capacity', models.IntegerField(default=10, verbose_name='Capacidade Total')),
                ('available_seats', models.IntegerField(verbose_name='Assentos Disponíveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.driver', verbose_name='Motorista')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tours.tour', verbose_name='Passeio')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'unique_together': {('tour', 'driver', 'date', 'time')},
            },
        ),
    ]
