# Generated by Django 5.1.5 on 2025-01-23 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_driver_tourschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourschedule',
            options={'verbose_name': 'Horário do Passeio', 'verbose_name_plural': 'Horários dos Passeios'},
        ),
        migrations.AlterUniqueTogether(
            name='tourschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driver',
            name='contact',
            field=models.CharField(blank=True, max_length=20, verbose_name='Contato'),
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='time',
        ),
        migrations.CreateModel(
            name='TourTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='tours.tourschedule', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Horário Específico',
                'verbose_name_plural': 'Horários Específicos',
                'unique_together': {('schedule', 'time')},
            },
        ),
    ]
