# Generated by Django 5.1.5 on 2025-01-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tourschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourschedule',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='time',
            field=models.JSONField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AlterUniqueTogether(
            name='tourschedule',
            unique_together={('tour', 'driver', 'date', 'time')},
        ),
        migrations.DeleteModel(
            name='TourTime',
        ),
    ]
