# Generated by Django 5.1.5 on 2025-01-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourschedule_options_tourschedule_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourschedule',
            unique_together={('tour', 'driver', 'date')},
        ),
        migrations.AlterField(
            model_name='tourschedule',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Horários'),
        ),
    ]
